// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.InteropServices;

namespace BIT.PilotlessPlane.Models.Underlying
{
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi, Pack = 1 /* Not Zero! */, Size = Global.FrameSize)]
    public struct FrameA
    {
        public byte z帧头0;
        public byte z帧头1;
        public byte z帧属性;
        public char z帧特征字;
        public short f俯仰角;
        public short f滚转角;
        public short c磁航向;
        public short g滚转角速率;
        public short p偏航角速率;
        public short f俯仰角速率;
        public short X轴线加速度;
        public short Y轴线加速度;
        public short Z轴线加速度;
        public short s升降舵量;
        public short f副翼舵量;
        public short f方向舵量;
        public byte y油门舵量;
        public byte s升降速度;
        public byte c超声波高度;
        public byte GPS时;
        public byte GPS分;
        public byte GPS秒;
        public byte z帧计数;
        public byte j校验和;
    }
}
