// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.InteropServices;

namespace BIT.PilotlessPlane.Models.Underlying
{
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi, Pack = 1 /* Not Zero! */, Size = Global.FrameSize)]
    public struct FrameB
    {
        public byte z帧头0;
        public byte z帧头1;
        public byte z帧属性;
        public char z帧特征字;
        public int GPS经度;
        public int GPS维度;
        public byte GPS地速;
        public ushort GPS地速方向;
        public ushort GPS高度;
        public short GPS升降速度;
        public byte GPS可见星数;
        public byte GPS工作状态;
        public short GPS东向速度;
        public short GPS北向速度;
        public sbyte f俯仰给定;
        public sbyte g滚转给定;
        public sbyte g高度积分;
        public sbyte f俯仰积分;
        public sbyte f滚转积分;
        public byte b备用30;
        public byte GPS时;
        public byte GPS分;
        public byte GPS秒;
        public byte z帧计数;
        public byte j校验和;
    }
}
